name: CI/CD Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0' # Use a compatible version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          npm run build --prod || (cat /home/runner/work/_temp/_github_home/_npm/_logs/*-debug.log && false) # Output npm debug log on failure

      - name: Build Docker image
        run: |
          docker build -t my-angular-app .
          docker tag my-angular-app:latest harshithffc/cicdangular:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Push Docker image to Docker Hub
        run: docker push harshithffc/cicdangular:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker pull harshithffc/cicdangular:latest
            docker stop $(docker ps -q --filter ancestor=harshithffc/cicdangular:latest)
            docker rm $(docker ps -q --filter ancestor=harshithffc/cicdangular:latest)
            docker run -d -p 4200:4200 harshithffc/cicdangular:latest
