name: CI/CD Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.0.0' # Use a stable version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          npm run build --prod || (cat /root/.npm/_logs/*-debug.log && false) # Output npm debug log on failure

      - name: Build Docker image
        run: |
          docker build -t my-angular-app .
          docker tag my-angular-app:latest harshithffc/CiCdAngular:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Push Docker image to Docker Hub
        run: docker push harshithffc/CiCdAngular:latest
